trigger: none

schedules:
  - cron: "0 14 * * 1" # Runs at 8/9 AM every Monday (converted from UTC to our timezone)
    displayName: "Weekly Monday trigger"
    always: true
    branches:
     include:
       - main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'
  
- script: |
    npm install puppeteer@23.3.0
  displayName: 'Install Puppeteer'
  
- task: Bash@3
  displayName: 'Verify Selectors'
  inputs:
    targetType: 'inline'
    script: |
      node verifyPage.js